.Dd December 18, 2020
.Dt ROC-OBJ-LS 1
.Os ROCm
.Sh NAME
.Nm roc-obj-ls
.Nd list URIs of embedded code objects
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Ar
.Sh DESCRIPTION
.Nm
lists the URIs of the code objects embedded in each host executable
.Ar file
to standard output, one per line.
.Bl -tag -width Fl
.It Fl h
Display this help and exit.
.It Fl v
Enable verbose output.
.El
.Sh EXAMPLES
Note: the following examples assume
.Pa a.so
and
.Pa b.so
exist and contain embedded code objects.
.Pp
To get a list of URIs of code objects embedded within a single code object:
.Bd -literal -offset indent
$ roc-obj-ls a.so
.Ed
.Pp
To get a more verbose listing of the previous example, including e.g. Entry IDs.
.Bd -literal -offset indent
$ roc-obj-ls -v a.so
.Ed
.Pp
To get a list of URIs of code objects embedded in each of multiple code objects:
.Bd -literal -offset indent
$ roc-obj-ls a.so b.so
.Ed
.Pp
To extract all code objects embedded within a code object, writing them to
uniquely named files in the current working directory:
.Bd -literal -offset indent
$ roc-obj-ls a.so | roc-obj-extract
.Ed
.Sh SEE ALSO
.Xr roc-obj-extract 1
