#!/bin/bash

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=2000000

fixssh() {
  eval "$(tmux show-env -s | grep '^SSH_')"
}
SSH_ENV=~/.ssh/env
start_agent() {
  touch "$SSH_ENV"
  chmod 600 "$SSH_ENV"
  ssh-agent | sed '/^echo/d' >"$SSH_ENV"
  . "$SSH_ENV"
  ssh-add
}
if [ -f "$SSH_ENV" ]; then
  . "$SSH_ENV"
  ps "$SSH_AGENT_PID" | grep -q ssh-agent || start_agent
else
  start_agent
fi

PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
GIT_PS1_SHOWCOLORHINTS=1
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1 '\\[\\033[00m\\]:\\[\\033[1\\\;36m\\]%s')\[\033[00m\]$ '

export EDITOR=nvim
export SVN_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR

[ -f /usr/local/etc/cc.env ] && . /usr/local/etc/cc.env

alias tmux='tmux -2'
alias less='less -R'

v() {
  nvim "$@"
}
f() {
  fd "$@"
}
c() {
  bat "$@"
}
g() {
  git "$@"
}
if [ -f /usr/share/bash-completion/completions/git ]; then
  . /usr/share/bash-completion/completions/git
  __git_complete g _git
fi
ldo() {
  "$@"
  if [ -d tools/clang ]; then
    cd tools/clang
    "$@"
    cd ../..
  fi
  if [ -d tools/lld ]; then
    cd tools/lld
    "$@"
    cd ../..
  fi
}
