#!/bin/bash

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=2000000

fixssh() {
  eval "$(tmux show-env -s | grep '^SSH_')"
}
SSH_ENV=~/.ssh/env
start_agent() {
  touch "$SSH_ENV"
  chmod 600 "$SSH_ENV"
  ssh-agent | sed '/^echo/d' >"$SSH_ENV"
  . "$SSH_ENV"
  ssh-add
}
if [ -f "$SSH_ENV" ]; then
  . "$SSH_ENV"
  ps "$SSH_AGENT_PID" | grep -q ssh-agent || start_agent
else
  start_agent
fi

PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
GIT_PS1_SHOWCOLORHINTS=1
extra_git_ps1() {
  local FORMAT="$1"
  local GIT_DIR
  GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
  if [[ -n $GIT_DIR && -x $GIT_DIR/hooks/commit-msg &&
	$(git config --local --bool --get gerrit.createChangeId) != false ]]; then
    printf "$FORMAT" "g"
  fi
}
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1 '\\[\\033[00m\\]:\\[\\033[1\\\;36m\\]%s')$(extra_git_ps1 '\\[\\033[00m\\]\\\+\\[\\033[1\\\;93m\\]%s\\[\\033[00m\\]')\[\033[00m\]$ '

export EDITOR=nvim
export SVN_EDITOR=$EDITOR
export BAT_THEME="Monokai Extended"

[ -f /usr/local/etc/cc.env ] && . /usr/local/etc/cc.env

alias tmux='tmux -2'
alias less='less -R'

v() {
  if [ $# -gt 0 ]; then
    if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
      nvr --nostart "$@"
    else
      nvim "$@"
    fi
  else
    if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
      printf "unset NVIM_LISTEN_ADDRESS and try again\n" >&2
      return 1
    fi
    nvim +term +starti
  fi
}
alias sp='nvr -o'
alias vsp='nvr -O'
alias tabe='nvr -p'
alias vd='nvr -d'
alias vp='nvr -l'
f() {
  fd "$@"
}
c() {
  bat "$@"
}
g() {
  git "$@"
}
if [ -f /usr/share/bash-completion/completions/git ]; then
  . /usr/share/bash-completion/completions/git
  __git_complete g _git
fi
ldo() {
  "$@"
  if [ -d tools/clang ]; then
    cd tools/clang
    "$@"
    cd ../..
  fi
  if [ -d tools/lld ]; then
    cd tools/lld
    "$@"
    cd ../..
  fi
}
gerrit() {
  if [[ $# -eq 0 ]]; then
    if [[ $(git config --local --bool --get gerrit.createChangeId) == false ]]; then
      git config --local --bool gerrit.createChangeId true
    else
      git config --local --bool gerrit.createChangeId false
    fi
  elif [[ $1 == 1 || $1 == on || $1 == true ]]; then
    git config --local --bool gerrit.createChangeId true
  elif [[ $1 == 0 || $1 == off || $1 == false ]]; then
    git config --local --bool gerrit.createChangeId false
  fi
}
bell() {
  echo -e '\a'
}

# Phabricator/arc try to be too clever, which would be nice if they failed
# less frequently. There also seems to be a lot of gotchas in the command-line
# workflow which do not seem to have been thought of upstream. Build a
# new set of primitives that "always work".

# If phab-pull fails we are left fending for ourselves to try to reconstruct
# the canonical commit message for a revision. Also, if the remote revision
# is updated by anyone else (i.e. they add themselves as a reviewer, or they
# add a tag) we may overwrite it accidentally if we fail to pull down the
# message before pushing. Add a simple way to fetch it.
# TODO: Automatically try to merge the upstream version and the local version
# before pushing.
phab-msg() {
  if [ $# -ne 1 ]; then
    printf "usage: phab-msg revision-id\n" >&2
    return 1
  fi
  local REV_ID
  REV_ID=$(printf "%s" "$1" | sed 's/^D\([0-9]\+\)$/\1/')
  printf '{ "revision_id": "%s" }' "$REV_ID" \
    | arc call-conduit differential.getcommitmessage \
    | jq -r '.["response"]'
}
phab-pull() {
  arc patch --skip-dependencies --nobranch "$@"
}
phab-push() {
  arc diff --edit --verbatim HEAD^
}

alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME:/dockerx -v $SSH_AUTH_SOCK:/ssh-auth-sock -e SSH_AUTH_SOCK=/ssh-auth-sock'

windows() {
  sudo grub-reboot "$(grep -i windows /boot/grub/grub.cfg | cut -d\' -f2 | head -1)" && sudo reboot
}
