"" Plug

call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'antiagainst/vim-tablegen'
Plug 'dag/vim-fish'
Plug 'embear/vim-localvimrc'
Plug 'gerw/vim-latex-suite'
Plug 'kien/ctrlp.vim'
Plug 'mattn/emmet-vim'
Plug 'neomake/neomake'
Plug 'ntpeters/vim-better-whitespace'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'rhysd/vim-clang-format'
Plug 'scott-linder/molokai'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'vim-scripts/a.vim'
Plug 'vimoutliner/vimoutliner'
call plug#end()

"" VIM

" Looks
colorscheme molokai
set fillchars=vert:│,fold:─,diff:─
set t_Co=256
set nohlsearch

" Lines
set colorcolumn=81,82
set nojoinspaces
set wrap
set linebreak

" Tabs
set expandtab
set tabstop=8
set shiftwidth=4

" Paragraphs
set formatoptions+=2

" Numbers
set number
set relativenumber

" Search
set incsearch
set ignorecase
set smartcase

" Modeline
set modeline

" Context
set scrolloff=2

" Remember last lines
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif

" Persistent undo
if isdirectory($HOME . '/.vim/undo') == 0
    :silent !mkdir -p ~/.vim/undo >/dev/null 2>&1
endif
set undodir=~/.vim/undo//
set undofile

" Doxygen comments
set comments-=://
set comments+=:///,://

" Terminal
:tnoremap <Esc> <C-\><C-n>

"" Plugins

" A
let g:alternateExtensions_cc = "hh"
let g:alternateExtensions_hh = "cc"

" Latex-Suite
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
let g:tex_comment_nospell = 1
let g:Tex_Folding = 0
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
let g:Tex_FormatDependancy_pdf = 'pdf'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'pdf'
let g:Tex_ViewRule_pdf = 'evince'

" NERDTree
nmap <C-n> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1

"" Filetype

" Python
au FileType python setl nosmartindent

" Markdown
au BufRead,BufNewFile *.md setl filetype=markdown spell
au FileType markdown noremap <buffer> <Leader>r :!markdown "%" > "$(basename "%" .md).html"<cr><cr>

" R
au FileType r noremap <buffer> <leader>r :!clear && R --vanilla <% \| less<cr>
au FileType r noremap <buffer> <leader>p :!evince Rplots.pdf >/dev/null 2>&1 &<cr>

" Rust
au FileType rust setl keywordprg=uzbl-rust-std
au FileType rust noremap <buffer> <leader>r :!clear && cargo run<cr>
au FileType rust noremap <buffer> <leader>t :!clear && cargo test<cr>
au FileType rust noremap <buffer> <leader>b :!clear && cargo build<cr>
au FileType rust noremap <buffer> <leader>c :!clear && cargo clean<cr>

" VimOutliner
au FileType votl set tabstop=2
au FileType votl set shiftwidth=2
au FileType votl set noexpandtab

" ClangFormat
"au FileType c,cpp nnoremap <buffer><Leader>f :<C-u>ClangFormat<CR>
au FileType c,cpp vnoremap <buffer><Leader>f :ClangFormat<CR>

" CtrlP
if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
endif

" NeoMake
call neomake#configure#automake('w')

" localvimrc
let g:localvimrc_persistent = 2

" terminal
tnoremap jj <C-\><C-n>

" alt+{hjkl} to navigate windows
:tnoremap <A-h> <C-\><C-N><C-w>h
:tnoremap <A-j> <C-\><C-N><C-w>j
:tnoremap <A-k> <C-\><C-N><C-w>k
:tnoremap <A-l> <C-\><C-N><C-w>l
:inoremap <A-h> <C-\><C-N><C-w>h
:inoremap <A-j> <C-\><C-N><C-w>j
:inoremap <A-k> <C-\><C-N><C-w>k
:inoremap <A-l> <C-\><C-N><C-w>l
:nnoremap <A-h> <C-w>h
:nnoremap <A-j> <C-w>j
:nnoremap <A-k> <C-w>k
:nnoremap <A-l> <C-w>l
