#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

./up

git add -A
git commit -m 'Bulk update'
git push origin main:main

for host in ixt-hq-58; do
    ssh "$host" 'git -C ~/dots pull; ~/dots/up'
done
