#!/bin/bash

set -xeuo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

readonly NVIM="$HOME/bin/nvim.appimage"
curl -sSLfo "$NVIM" 'https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage'
chmod a+x "$NVIM"
for alt in ex vi view vim vimdiff nvim; do
  ln -sf "$NVIM" "$HOME/bin/$alt"
done

curl -sSLf \
    'https://github.com/dandavison/delta/releases/download/0.15.1/delta-0.15.1-x86_64-unknown-linux-musl.tar.gz' \
  | tar -C "$HOME"/bin -z --get --strip-components=1 delta-0.15.1-x86_64-unknown-linux-musl/delta

rm -rf "$HOME/.local"
mkdir -p "$HOME/.local/"{tmp,opt}

curl -sSLfo "$HOME/.local/tmp/clangd.zip" \
    'https://github.com/clangd/clangd/releases/download/15.0.6/clangd-linux-15.0.6.zip'
unzip -qqod "$HOME/.local/tmp" "$HOME/.local/tmp/clangd.zip"
rsync -a "$HOME/.local/tmp/clangd_"*/ "$HOME/.local"

curl -sSLfo "$HOME/.local/tmp/arcanist.zip" \
  'https://github.com/phacility/arcanist/archive/refs/heads/master.zip'
unzip -qqod "$HOME/.local/opt" "$HOME/.local/tmp/arcanist.zip"
ln -sf "$HOME/.local/opt/arcanist-master/bin/arc" "$HOME/bin/arc"

curl -sSLfo "$HOME/.local/tmp/mold.tar.gz" \
    'https://github.com/rui314/mold/releases/download/v2.0.0/mold-2.0.0-x86_64-linux.tar.gz'
tar -C "$HOME/.local/tmp" -xzf "$HOME/.local/tmp/mold.tar.gz"
rsync -a "$HOME/.local/tmp/mold-"*/ "$HOME/.local"

curl -sSLfo "$HOME/.local/tmp/gh.tar.gz" \
    'https://github.com/cli/cli/releases/download/v2.34.0/gh_2.34.0_linux_amd64.tar.gz'
tar -C "$HOME/.local/tmp" -xzf "$HOME/.local/tmp/gh.tar.gz"
rsync -a "$HOME/.local/tmp/gh_"*/ "$HOME/.local"

pip3 -q install --user --upgrade pip neovim-remote cmake

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
mkdir -p "$CONFIG_HOME"
for d in dots/*; do
  if [ -d "$d" ]; then
    ln -sf "$(readlink -f "$d")" -t "$CONFIG_HOME"
  else
    ln -sf "$(readlink -f "$d")" ~/."$(basename "$d")"
  fi
done

mkdir -p ~/bin
for b in bin/*; do
  ln -sf "$(readlink -f "$b")" ~/bin/"$(basename "$b")"
done
ln -sf "$(readlink -f up)" ~/bin/up

PLUG="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
if [ ! -f "$PLUG" ]; then
  curl -sSLfo "$PLUG" --create-dirs \
    'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
