[tools]
"aqua:MordechaiHadad/bob" = "4.1.6"
"aqua:atuin" = "18.10.0"
"aqua:bat" = "0.26.1"
"aqua:cmake" = "4.2.1"
"aqua:delta" = "0.18.1"
"aqua:fd" = "10.3.0"
"aqua:fzf" = "0.67.0"
"aqua:lua-language-server" = "3.16.4"
"aqua:ninja-build/ninja" = "1.13.2"
"aqua:ripgrep" = "15.1.0"
"aqua:starship" = "1.24.1"
"aqua:uv" = "0.9.18"
gh = "2.86.0"
"github:noborus/ov" = "0.50.2"
"github:rr-debugger/rr" = "5.9.0"
hyperfine = "1.20.0"
rust = "1.93.0"
rust-analyzer = "2026-01-26"
