#!/bin/bash

# Abuse ~/.bash_aliases as the one place to configure bash. This assumes that
# whatever file bash sources for login shells (i.e. /etc/profile, ~/.profile or
# ~/.bash_profile) and interactive shells (i.e. ~/.bashrc) includes this file,
# directly or indirectly. This seems to be the case for e.g. modern Ubuntu.

[[ -x ~/.local/bin/mise ]] && eval "$(~/.local/bin/mise activate bash)"
hash starship >/dev/null 2>&1 && eval "$(starship init bash)"
if hash atuin >/dev/null 2>&1 && [[ -f ~/.bash-preexec.sh ]]; then
  unset HISTFILE
  source ~/.bash-preexec.sh
  eval "$(atuin init bash --disable-up-arrow)"
fi

readonly SSH_ENV=~/.ssh/env
sshid-start-agent() {
  touch "$SSH_ENV"
  chmod 600 "$SSH_ENV"
  ssh-agent | sed '/^echo/d' >"$SSH_ENV"
  . "$SSH_ENV"
}
sshid-list() {
  ssh-add -L
}
sshid-clear() {
  ssh-add -D
}
sshid-public() {
  sshid-clear
  ssh-add ~/.ssh/id_ed25519
}
sshid-amdeng() {
  sshid-clear
  ssh-add ~/.ssh/id_ed25519_amdeng
}
sshid-init() {
  if [ -f ~/.ssh/id_ed25519 ]; then
    if [ -f "$SSH_ENV" ]; then
      . "$SSH_ENV"
      ps "$SSH_AGENT_PID" | grep -q ssh-agent || sshid-start-agent
    else
      sshid-start-agent
    fi
  else
    if [[ -S "$SSH_AUTH_SOCK" && ! -L "$SSH_AUTH_SOCK" ]]; then
      ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
    fi
    export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
  fi
}
sshid-init

export EDITOR='v --wait'
export GIT_EDITOR=$EDITOR
export SVN_EDITOR=$EDITOR

export PAGER='ov'

export BAT_THEME="Monokai Extended"

alias tmux='tmux -2'

mosh-kill() {
  ps xo comm,pid --sort etime --no-header | awk '$1~/^mosh-server$/ { if (old) print $2; else old=1; }' | xargs -r kill
}

alias g=git
if [ -f /usr/share/bash-completion/completions/git ]; then
  . /usr/share/bash-completion/completions/git
  __git_complete g __git_main
fi
alias a='tput bel'
alias drun='docker run -it --rm --network=host --dns 8.8.8.8 --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME:/dockerx -v $SSH_AUTH_SOCK:/ssh-auth-sock -e SSH_AUTH_SOCK=/ssh-auth-sock'

c() {
  local SOURCE=''
  [[ $# -gt 0 ]] && { SOURCE="$1"; shift; }
  PREAMBLE="#include <stdint.h>\n"
  for bits in 8 16 32 64; do
    PREAMBLE+="typedef int${bits}_t i${bits};\n"
    PREAMBLE+="typedef uint${bits}_t u${bits};\n"
  done
  printf "${PREAMBLE}\n%s" "$SOURCE" | clang -x c - -S -o - --target=aarch64-unknown-linux "$@" 2>&1
}

ocl() {
  local SOURCE=''
  [[ $# -gt 0 ]] && { SOURCE="$1"; shift; }
  printf '%s' "$SOURCE" | clang -x cl -Xclang -finclude-default-header - -O0 -S -o - --target=amdgcn-amd-amdhsa -mcpu=gfx900 "$@" 2>&1 | sed -e '/^!opencl.ocl.version/d' -e '/^!llvm.ident/d'
}

hip() {
  local SOURCE=''
  [[ $# -gt 0 ]] && { SOURCE="$1"; shift; }
  printf '%s' "$SOURCE" | clang -x hip --cuda-device-only - -O0 -S -o - --cuda-gpu-arch=gfx900 "$@" 2>&1 | sed '/\t\.ident/d'
}

export PATH="${PATH%%:/mnt/c*}"
